### ISSUE TITLE
db 상 max_pay 값이 4010, 5010 등으로 저장되어 있는 문제

### ISSUE THREAD

**Issue by munkyu** [okjsp/okky-jobs#1]
max_pay 값이 실제 okky 홈페이지에는 그렇지 않는데 dump db 상에서는 다른 값으로 세팅이 되어 있습니다. 예를들어  https://okky.kr/recruit/417545 의 경우 max_pay 는 70 이여야 하는데 db 상에서는 6010 으로 되어 있습니다.

**Comment by chlrbgh89** [comment]
찾아보니, 제가 잘못된 정보를 드렸습니다 ㅠㅠ 죄송합니다.

- recruit테이블 job_type 값이 FULLTIME(정규직)일 때, minPay ~ maxPay 값을 갖습니다.
이 때, minPay와 maxPay의 값은 아래와 같습니다.
```
jobPosition.minPay.year.20=2000만 이상
jobPosition.minPay.year.30=3000만 이상
jobPosition.minPay.year.40=4000만 이상
jobPosition.minPay.year.50=5000만 이상
jobPosition.minPay.year.60=6000만 이상
jobPosition.minPay.year.70=7000만 이상
jobPosition.minPay.year.80=8000만 이상
jobPosition.minPay.year.90=9000만 이상
jobPosition.minPay.year.100=1억 이상

jobPosition.maxPay.year.30=3000만 미만
jobPosition.maxPay.year.40=4000만 미만
jobPosition.maxPay.year.50=5000만 미만
jobPosition.maxPay.year.60=6000만 미만
jobPosition.maxPay.year.70=7000만 미만
jobPosition.maxPay.year.80=8000만 미만
jobPosition.maxPay.year.90=9000만 미만
jobPosition.maxPay.year.100=1억 미만
jobPosition.maxPay.year.999=협의
```
ex) minPay = 30, maxPay = 60  >> 3000만 이상 ~ 6000만 미만

- recruit테이블 job_type 값이 CONTRACT(계약직)일 때, minPay값으로만 계산됩니다.
이 때, minPay 값은 아래와 같습니다.
```
jobPosition.minPay.month.20=200만 이상 ~ 300만 미만
jobPosition.minPay.month.30=300만 이상 ~ 400만 미만
jobPosition.minPay.month.40=400만 이상 ~ 500만 미만
jobPosition.minPay.month.50=500만 이상 ~ 600만 미만
jobPosition.minPay.month.60=600만 이상 ~ 700만 미만
jobPosition.minPay.month.70=700만 이상 ~ 800만 미만
jobPosition.minPay.month.80=800만 이상 ~ 900만 미만
jobPosition.minPay.month.90=900만 이상
```

참고자료
[https://github.com/okjsp/okky/blob/18b79cc6db3f4820496851adda8ba3fb190848fe/grails-app/i18n/messages.properties#L109](https://github.com/okjsp/okky/blob/18b79cc6db3f4820496851adda8ba3fb190848fe/grails-app/i18n/messages.properties#L109)

관련메일 작성해서 다른분들에게도 공유하겠습니다.
감사합니다!!

**Comment by munkyu** [comment]
위 내용 아래 커밋으로 반영함
https://github.com/okjsp/okky-jobs/commit/2112b0201f28fbee4e452e4faafd4d2f216bd461
