### ISSUE TITLE
start_date 와 working_month 를 더해서 end_date 를 계산

### ISSUE THREAD

**Issue by munkyu** [okjsp/okky-jobs#2]
start_date: 2017/07
working_month: 6
의 경우 계산해서
end_date: 2018/01 로 필드를 하나 만들어 주면 좋을 것 같습니다.

**Comment by hyosoonkim** [comment]
해당버전 적용하여, 커밋완료 하였습니다. 
- okky_jobs.conf 파일 확인

**Comment by munkyu** [comment]
확인했습니다
