### ISSUE TITLE
tag_string 대소문자 구분이 없도록 처리하기

### ISSUE THREAD

**Issue by munkyu** [okjsp/okky-jobs#3]
현재 tag_string의 경우 java JAVA 등 대소문자가 구분되어 들어가는데 집계할 경우에 각기 다른 아이템으로 처리되기 때문에 analyzer를 통하거나 logstash의 filter를 통해서 대소문자 구분이 안되도록 처리하는 게 좋을 것 같습니다.

**Comment by eltreeKM** [comment]
tag_string의 필드타입을 text로 변경하고
nori analyzer에 lowercase 필터를 추가했습니다.
대소문자 관계없이 검색 가능하고 결과도 대소문자 관계없이 리턴 됩니다.
데이터는 따로 okky-jobs-data-km 으로 리인덱스 했습니다.

**Comment by kimjmin** [comment]
Keyword 타입에는 노말라이저를 적용하시면 됩니다.

https://esbook.kimjmin.net/07-settings-and-mappings/7.2-mappings/7.2.1#keyword

**Comment by hyosoonkim** [comment]
lowercase 적용하여, 대소문자 변경할수 있도록 함 
- okky_job templates 파일 확인

**Comment by munkyu** [comment]
제가 logstash에서 소문자로 변환해서 es에 넣도록 처리했습니다.(https://github.com/okjsp/okky-jobs/commit/1dfd0c4406af8e136b7bac304c953c8c454f8747) 이 이슈는 닫을께요
